// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWPPFovoevvGiS5Z0fRpavxg_2yPe9oPQ',
    appId: '1:620234940540:web:cc013ddeea09e654bda9f9',
    messagingSenderId: '620234940540',
    projectId: 'yaadein-with-serverpod',
    authDomain: 'yaadein-with-serverpod.firebaseapp.com',
    storageBucket: 'yaadein-with-serverpod.appspot.com',
    measurementId: 'G-DTEX75M31C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkYUGGmh03ERvfXOayqbskSWT_sndwDE',
    appId: '1:620234940540:android:738850d1be70a621bda9f9',
    messagingSenderId: '620234940540',
    projectId: 'yaadein-with-serverpod',
    storageBucket: 'yaadein-with-serverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj1NbNiQIfns2-a3bcY8dUqXtOH810WA4',
    appId: '1:620234940540:ios:9d3e8586b1072054bda9f9',
    messagingSenderId: '620234940540',
    projectId: 'yaadein-with-serverpod',
    storageBucket: 'yaadein-with-serverpod.appspot.com',
    iosClientId: '620234940540-utgbm5ovgogahr1bpb6eo4qko95tp158.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj1NbNiQIfns2-a3bcY8dUqXtOH810WA4',
    appId: '1:620234940540:ios:8cd832fc6ca51564bda9f9',
    messagingSenderId: '620234940540',
    projectId: 'yaadein-with-serverpod',
    storageBucket: 'yaadein-with-serverpod.appspot.com',
    iosClientId: '620234940540-fv8ban56bsujhs84ul7dg21ng4r5hs5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementFlutter.RunnerTests',
  );
}
